# Testing Out Supabase Client

In [1]:
import os
import pandas as pd
from supabase import create_client, Client

url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_SERVICE_KEY")
supabase: Client = create_client(url, key)

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

In [2]:

response = supabase.table('station_isochrones').select("*").execute()
data,_ = response
data[1]
df = pd.DataFrame(data[1])
df

,isochrone_id,value,center,area,reachfactor,total_pop,type,station_id,geometry
0,1300,300,"[101.69396136409445, 3.1394620891138714]",0.000018,0.6523,1318.0,Polygon,1,"{'type': 'Polygon', 'coordinates': [[[101.6910..."
1,1600,600,"[101.69396136409445, 3.1394620891138714]",0.000089,0.7863,6331.0,Polygon,1,"{'type': 'Polygon', 'coordinates': [[[101.6877..."
2,1900,900,"[101.69396136409445, 3.1394620891138714]",0.000228,0.8979,16758.0,Polygon,1,"{'type': 'Polygon', 'coordinates': [[[101.6847..."
3,2300,300,"[101.69293232544325, 3.1545974065434557]",0.000023,0.8278,3527.0,Polygon,2,"{'type': 'Polygon', 'coordinates': [[[101.6915..."
4,2600,600,"[101.69293232544325, 3.1545974065434557]",0.000097,0.8608,10737.0,Polygon,2,"{'type': 'Polygon', 'coordinates': [[[101.6871..."
...,...,...,...,...,...,...,...,...,...
586,196600,600,"[101.6121709, 3.0827827]",0.000058,0.5128,5979.0,Polygon,196,"{'type': 'Polygon', 'coordinates': [[[101.6053..."
587,196900,900,"[101.6121709, 3.0827827]",0.000131,0.5142,12866.0,Polygon,196,"{'type': 'Polygon', 'coordinates': [[[101.6024..."
588,197300,300,"[101.61027804441044, 3.0761293729574577]",0.000025,0.8959,3478.0,Polygon,197,"{'type': 'Polygon', 'coordinates': [[[101.6069..."
589,197600,600,"[101.61027804441044, 3.0761293729574577]",0.000078,0.6875,9864.0,Polygon,197,"{'type': 'Polygon', 'coordinates': [[[101.6035..."
590,197900,900,"[101.61027804441044, 3.0761293729574577]",0.000163,0.6435,20356.0,Polygon,197,"{'type': 'Polygon', 'coordinates': [[[101.6001..."